# Generated by Django 5.0.6 on 2024-05-23 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tiposUsuarios',
            fields=[
                ('idTipoUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('estatus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=20)),
                ('fechaAlta', models.DateTimeField()),
                ('idTipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.tiposusuarios')),
            ],
        ),
    ]
