# Generated by Django 5.0.6 on 2024-05-23 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='estados',
            fields=[
                ('idEstado', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEstado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='paises',
            fields=[
                ('idPais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='municipios',
            fields=[
                ('idMunicipio', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMunicipio', models.CharField(max_length=20)),
                ('idEstado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Persona.estados')),
            ],
        ),
        migrations.CreateModel(
            name='colonias',
            fields=[
                ('idColonia', models.AutoField(primary_key=True, serialize=False)),
                ('nombreColonia', models.CharField(max_length=20)),
                ('cp', models.CharField(max_length=5)),
                ('idMunicipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Persona.municipios')),
            ],
        ),
        migrations.AddField(
            model_name='estados',
            name='idPais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Persona.paises'),
        ),
        migrations.CreateModel(
            name='personas',
            fields=[
                ('idPersona', models.AutoField(primary_key=True, serialize=False)),
                ('curp', models.CharField(max_length=18)),
                ('nombre', models.CharField(max_length=30)),
                ('ape1', models.CharField(max_length=30)),
                ('ape2', models.CharField(max_length=30)),
                ('calle', models.CharField(max_length=30)),
                ('numero', models.CharField(max_length=5)),
                ('zona', models.IntegerField()),
                ('cp', models.CharField(max_length=5)),
                ('nacionalidad', models.IntegerField()),
                ('sexo', models.IntegerField()),
                ('estatus', models.IntegerField()),
                ('telCasa', models.CharField(max_length=10)),
                ('telCelular', models.CharField(max_length=10)),
                ('estadoCivil', models.IntegerField()),
                ('correo', models.CharField(max_length=80)),
                ('idColonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Persona.colonias')),
                ('idMunicipioNacimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Persona.municipios')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuarios')),
            ],
        ),
    ]
