# Generated by Django 5.0.6 on 2024-06-07 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleado', '0002_rename_idtitulo_titulosacademicos_idtitulo'),
        ('Persona', '0002_personas_hijos_alter_personas_ape2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name='carreras',
            fields=[
                ('idCarrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCarrera', models.CharField(max_length=80)),
                ('siglas', models.CharField(max_length=10)),
                ('estatus', models.IntegerField()),
                ('nivel', models.IntegerField()),
                ('area', models.CharField(max_length=10)),
                ('clave', models.CharField(max_length=10)),
                ('modalidad', models.IntegerField()),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleado.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='capacidadAtencion',
            fields=[
                ('idCapacidad', models.AutoField(primary_key=True, serialize=False)),
                ('capacidadAtencion', models.IntegerField()),
                ('proyeccionFichas', models.IntegerField()),
                ('grupos', models.IntegerField()),
                ('ciclo', models.CharField(max_length=9)),
                ('idCarrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Persona.carreras')),
            ],
        ),
    ]
