# Generated by Django 5.0.6 on 2024-06-07 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0003_alter_personas_nombre_carreras_capacidadatencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreras',
            name='nombreCarrera',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='datosMedicos',
            fields=[
                ('idDatosMedicos', models.AutoField(primary_key=True, serialize=False)),
                ('peso', models.FloatField()),
                ('estatura', models.IntegerField()),
                ('famDiabeticos', models.IntegerField(null=True)),
                ('famHipertensos', models.IntegerField(null=True)),
                ('famCardiacos', models.IntegerField(null=True)),
                ('tipoSangre', models.IntegerField()),
                ('idPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Persona.personas')),
            ],
        ),
    ]
