# Generated by Django 5.0.6 on 2024-06-05 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Persona', '0002_personas_hijos_alter_personas_ape2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='areasEmpleados',
            fields=[
                ('idArea', models.AutoField(primary_key=True, serialize=False)),
                ('nombreArea', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='puestosEmpleado',
            fields=[
                ('idPuestoEmpleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePuesto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='titulosAcademicos',
            fields=[
                ('idtitulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='empleados',
            fields=[
                ('idEmpleado', models.AutoField(primary_key=True, serialize=False)),
                ('numeroEmpleado', models.CharField(max_length=15)),
                ('fechaAlta', models.DateField()),
                ('rfc', models.CharField(max_length=15)),
                ('estatus', models.IntegerField()),
                ('idArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleado.areasempleados')),
                ('idPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Persona.personas')),
                ('idPuestoEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleado.puestosempleado')),
                ('idTitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleado.titulosacademicos')),
            ],
        ),
    ]
