# Generated by Django 5.0.6 on 2024-06-06 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empleado', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titulosacademicos',
            old_name='idtitulo',
            new_name='idTitulo',
        ),
    ]
