# Generated by Django 5.0.6 on 2024-06-07 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleado', '0002_rename_idtitulo_titulosacademicos_idtitulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='documentosEmpleado',
            fields=[
                ('idDocEmpleado', models.AutoField(primary_key=True, serialize=False)),
                ('acta', models.CharField(max_length=20, null=True)),
                ('domicilio', models.CharField(max_length=20, null=True)),
                ('curp', models.CharField(max_length=20, null=True)),
                ('credencial', models.CharField(max_length=20, null=True)),
                ('cartilla', models.CharField(max_length=20, null=True)),
                ('licencia', models.CharField(max_length=20, null=True)),
                ('aPenales', models.CharField(max_length=20, null=True)),
                ('aDisciplinarios', models.CharField(max_length=20, null=True)),
                ('recomentacion1', models.CharField(max_length=20, null=True)),
                ('recomentacion2', models.CharField(max_length=20, null=True)),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleado.empleados')),
            ],
        ),
    ]
