# Generated by Django 5.0.6 on 2024-05-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='periodo',
            fields=[
                ('idPeriodo', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('activo', models.IntegerField()),
                ('genTSU', models.IntegerField()),
                ('genING', models.IntegerField()),
            ],
        ),
    ]
