# Generated by Django 5.0.6 on 2024-06-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='activo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
