# Generated by Django 5.0.6 on 2024-06-07 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0002_alter_periodo_activo'),
        ('Empleado', '0003_documentosempleado'),
        ('Persona', '0004_alter_carreras_nombrecarrera_datosmedicos'),
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='estatusAlumnos',
            fields=[
                ('idEstatusAlumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEstatus', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='grupos',
            fields=[
                ('idGrupo', models.AutoField(primary_key=True, serialize=False)),
                ('grado', models.SmallIntegerField()),
                ('grupo', models.CharField(max_length=1)),
                ('turno', models.SmallIntegerField()),
                ('idCarrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Persona.carreras')),
                ('idMaestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleado.empleados')),
                ('idPeriodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10)),
                ('nivel', models.SmallIntegerField()),
                ('fechaAlta', models.DateField()),
                ('idPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Persona.personas')),
                ('idUsuarioInscribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuarios')),
                ('periodoInicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.periodo')),
                ('idEstatusAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.estatusalumnos')),
                ('idGrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.grupos')),
            ],
        ),
    ]
