# Generated by Django 5.0.6 on 2024-05-29 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alumno', '0001_initial'),
        ('Persona', '0002_personas_hijos_alter_personas_ape2_and_more'),
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carreras',
            fields=[
                ('idCarrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCarrera', models.CharField(max_length=80)),
                ('siglas', models.CharField(max_length=10)),
                ('estatus', models.IntegerField()),
                ('nivel', models.IntegerField()),
                ('area', models.CharField(max_length=10)),
                ('director', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='otrosDatos',
            fields=[
                ('idDato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('tipo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='subsistemas',
            fields=[
                ('idSubsistema', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='aspirantes',
            fields=[
                ('idAspirante', models.AutoField(primary_key=True, serialize=False)),
                ('añoIngresoPrepa', models.CharField(max_length=5)),
                ('añoEgresoPrepa', models.CharField(max_length=5)),
                ('promedioPrepa', models.CharField(max_length=5)),
                ('especialidadPrepa', models.CharField(max_length=30)),
                ('nombreTutor', models.CharField(max_length=30)),
                ('ape1Tutor', models.CharField(max_length=30)),
                ('ape2Tutor', models.CharField(max_length=30, null=True)),
                ('folioCeneval', models.CharField(max_length=30)),
                ('folioPagoFicha', models.CharField(max_length=30)),
                ('fechaRegistro', models.DateField()),
                ('nivel', models.IntegerField()),
                ('estatus', models.IntegerField()),
                ('idPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Persona.personas')),
                ('idUsuarioRegistra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='datosMedicos',
            fields=[
                ('idDatosMedicos', models.AutoField(primary_key=True, serialize=False)),
                ('peso', models.FloatField()),
                ('estatura', models.IntegerField()),
                ('famDiabeticos', models.IntegerField(null=True)),
                ('famHipertensos', models.IntegerField(null=True)),
                ('famCardiacos', models.IntegerField(null=True)),
                ('tipoSangre', models.IntegerField()),
                ('idAspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aspirante.aspirantes')),
            ],
        ),
        migrations.CreateModel(
            name='documentos',
            fields=[
                ('idDocumento', models.AutoField(primary_key=True, serialize=False)),
                ('acta', models.CharField(max_length=20)),
                ('curp', models.CharField(max_length=20)),
                ('foto', models.CharField(max_length=20)),
                ('certificadoBachillerato', models.CharField(max_length=20, null=True)),
                ('constancia', models.CharField(max_length=20, null=True)),
                ('analisisSanguineo', models.CharField(max_length=20, null=True)),
                ('idAspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aspirante.aspirantes')),
            ],
        ),
        migrations.CreateModel(
            name='documentoCondicionado',
            fields=[
                ('idDocumentoCondicionado', models.AutoField(primary_key=True, serialize=False)),
                ('fechaEntrega', models.DateField()),
                ('estatus', models.IntegerField()),
                ('idDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aspirante.documentos')),
            ],
        ),
        migrations.CreateModel(
            name='encuesta',
            fields=[
                ('idEncuesta', models.AutoField(primary_key=True, serialize=False)),
                ('enterarUniversidad', models.IntegerField()),
                ('medioEntregaFicha', models.IntegerField()),
                ('razonInscripcion', models.IntegerField()),
                ('otraUniversidad', models.IntegerField(null=True)),
                ('idAspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aspirante.aspirantes')),
                ('idCarrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrera1', to='Aspirante.carreras')),
                ('idCarrera2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrera2', to='Aspirante.carreras')),
            ],
        ),
        migrations.CreateModel(
            name='escuelasProcedencia',
            fields=[
                ('idEscuelaProcedencia', models.AutoField(primary_key=True, serialize=False)),
                ('claveEscuela', models.CharField(max_length=30)),
                ('nombreEscuela', models.CharField(max_length=100)),
                ('direccionEscuela', models.CharField(max_length=100)),
                ('telefonoEscuela', models.CharField(max_length=12)),
                ('estatus', models.IntegerField()),
                ('municipioEscuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Persona.municipios')),
                ('idSubsistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aspirante.subsistemas')),
            ],
        ),
        migrations.AddField(
            model_name='aspirantes',
            name='idEscuelaProcedencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aspirante.escuelasprocedencia'),
        ),
        migrations.CreateModel(
            name='detalleOtroDato',
            fields=[
                ('idDetDato', models.AutoField(primary_key=True, serialize=False)),
                ('idAspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aspirante.aspirantes')),
                ('idDato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aspirante.otrosdatos')),
            ],
        ),
        migrations.CreateModel(
            name='procesosFichas',
            fields=[
                ('idProcesoFicha', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicioFicha', models.DateField()),
                ('fechaFinFicha', models.DateField()),
                ('fechaExani', models.DateField()),
                ('horaExani', models.TimeField()),
                ('lugarAplicacion', models.CharField(max_length=50)),
                ('PeriodoInicioClases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.periodo')),
            ],
        ),
        migrations.AddField(
            model_name='aspirantes',
            name='idProcesoFicha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aspirante.procesosfichas'),
        ),
        migrations.CreateModel(
            name='universidades',
            fields=[
                ('idUniversidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('siglas', models.CharField(max_length=10, null=True)),
                ('estatus', models.IntegerField()),
                ('nombreRector', models.CharField(max_length=100, null=True)),
                ('municipioUniversidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Persona.municipios')),
            ],
        ),
    ]
