# Generated by Django 5.0.6 on 2024-06-05 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aspirante', '0002_documentos_actaf_documentos_analisissanguineof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreras',
            name='director',
        ),
    ]
