# Generated by Django 5.0.6 on 2024-06-05 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aspirante', '0003_remove_carreras_director'),
        ('Empleado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreras',
            name='idEmpleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Empleado.empleados'),
            preserve_default=False,
        ),
    ]
