# Generated by Django 5.0.6 on 2024-06-07 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aspirante', '0006_remove_capacidadatencion_idcarrera_and_more'),
        ('Persona', '0003_alter_personas_nombre_carreras_capacidadatencion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='capacidadAtencion',
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='idCarrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrera1', to='Persona.carreras'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='idCarrera2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrera2', to='Persona.carreras'),
        ),
        migrations.DeleteModel(
            name='carreras',
        ),
    ]
