# Generated by Django 5.0.6 on 2024-06-07 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aspirante', '0007_delete_capacidadatencion_alter_encuesta_idcarrera_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='datosMedicos',
        ),
    ]
